version: 2.1

jobs:
  build:
    docker:
      - image: google/dart:2.9.1

    steps:
      - checkout
      
      - run:
          name: Install Dart SDK
          command: |
            apt-get update
            apt-get install -y apt-transport-https
            sh -c 'wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'
            sh -c 'wget -qO- https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list'
            apt-get update
            apt-get install -y dart
            
      - run:
          name: Install dependencies
          command: dart pub get

      - run:
          name: Run tests and analyze
          command: dart test && dart analyze

workflows:
  version: 2
  build:
    jobs:
      - build
